//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestoranProje.Properties {
    using System;
    
    
    /// <summary>
    ///   Yerelleştirilmiş dizeleri aramak gibi işlemler için, türü kesin olarak belirtilmiş kaynak sınıfı.
    /// </summary>
    // Bu sınıf ResGen veya Visual Studio gibi bir araç kullanılarak StronglyTypedResourceBuilder
    // sınıfı tarafından otomatik olarak oluşturuldu.
    // Üye eklemek veya kaldırmak için .ResX dosyanızı düzenleyin ve sonra da ResGen
    // komutunu /str seçeneğiyle yeniden çalıştırın veya VS projenizi yeniden oluşturun.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Bu sınıf tarafından kullanılan, önbelleğe alınmış ResourceManager örneğini döndürür.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RestoranProje.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Tümü için geçerli iş parçacığının CurrentUICulture özelliğini geçersiz kular
        ///   CurrentUICulture özelliğini tüm kaynak aramaları için geçersiz kılar.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap _0523_Mediterranean_diet_CV_jpg_225x526 {
            get {
                object obj = ResourceManager.GetObject("0523_Mediterranean_diet_CV.jpg_225x526", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap _1a0a04b2_e570_4919_9799_86128fe27a9a_thumb_110x88 {
            get {
                object obj = ResourceManager.GetObject("1a0a04b2-e570-4919-9799-86128fe27a9a_thumb_110x88", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap _21335c16_1483_4229_a265_aa4783dbb12b_thumb_110x88 {
            get {
                object obj = ResourceManager.GetObject("21335c16-1483-4229-a265-aa4783dbb12b_thumb_110x88", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap _2958eabc_adc2_4f53_bfea_81ec542cdd3f_110x88 {
            get {
                object obj = ResourceManager.GetObject("2958eabc-adc2-4f53-bfea-81ec542cdd3f_110x88", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap _4_peynirli_pizza_110x88 {
            get {
                object obj = ResourceManager.GetObject("4-peynirli-pizza_110x88", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap _523173_stock_photo_sex_on_the_beach_225x526 {
            get {
                object obj = ResourceManager.GetObject("523173_stock-photo-sex-on-the-beach_225x526", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap _5321682b_d04b_4e2e_8265_4f248f11de96_thumb_110x88 {
            get {
                object obj = ResourceManager.GetObject("5321682b-d04b-4e2e-8265-4f248f11de96_thumb_110x88", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap _56124786_090f_47bf_80fb_1e81c4e62a28_110x88 {
            get {
                object obj = ResourceManager.GetObject("56124786-090f-47bf-80fb-1e81c4e62a28_110x88", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap _56124786_090f_47bf_80fb_1e81c4e62a28_110x881 {
            get {
                object obj = ResourceManager.GetObject("56124786-090f-47bf-80fb-1e81c4e62a28_110x881", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap _7bc6162d_8454_419d_aa5a_301f9efa2346_thumb_110x88 {
            get {
                object obj = ResourceManager.GetObject("7bc6162d-8454-419d-aa5a-301f9efa2346_thumb_110x88", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap Ahududu_Hibiscus_Buzlu_Çayy_110x88 {
            get {
                object obj = ResourceManager.GetObject("Ahududu-Hibiscus-Buzlu-Çayy_110x88", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap americano1_110x88 {
            get {
                object obj = ResourceManager.GetObject("americano1_110x88", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap BALIKsomon_ipsanak_patates_detay_110x88 {
            get {
                object obj = ResourceManager.GetObject("BALIKsomon-ipsanak-patates-detay_110x88", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap bL9bBC9H_110x88 {
            get {
                object obj = ResourceManager.GetObject("bL9bBC9H_110x88", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap bonfile_salata_110x88 {
            get {
                object obj = ResourceManager.GetObject("bonfile-salata_110x88", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap brosslife_unsuz_şekersiz_brovnie_110x88 {
            get {
                object obj = ResourceManager.GetObject("brosslife-unsuz-şekersiz-brovnie_110x88", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap cikolatali_sufle_cafe_225x526 {
            get {
                object obj = ResourceManager.GetObject("cikolatali-sufle-cafe_225x526", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap ÇikolatalıMikshake_110x88 {
            get {
                object obj = ResourceManager.GetObject("ÇikolatalıMikshake_110x88", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap ÇikolatalıMikshake_110x881 {
            get {
                object obj = ResourceManager.GetObject("ÇikolatalıMikshake_110x881", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap çıtır_tavuk_taco_110x88 {
            get {
                object obj = ResourceManager.GetObject("çıtır-tavuk-taco_110x88", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap db50d1f3_8a33_495a_bc3f_e809a3bd7c24_thumb_110x88 {
            get {
                object obj = ResourceManager.GetObject("db50d1f3-8a33-495a-bc3f-e809a3bd7c24_thumb_110x88", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap e1f1f757_1bc9_4e99_9c97_7a6ee2c3ea30_thumb_110x88 {
            get {
                object obj = ResourceManager.GetObject("e1f1f757-1bc9-4e99-9c97-7a6ee2c3ea30_thumb_110x88", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap f94ea2be_3b7b_4f58_84bd_14a8e523853e_110x88 {
            get {
                object obj = ResourceManager.GetObject("f94ea2be-3b7b-4f58-84bd-14a8e523853e_110x88", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap fe225549_a3ec_4369_9463_75efbda3dfbc_thumb_110x88 {
            get {
                object obj = ResourceManager.GetObject("fe225549-a3ec-4369-9463-75efbda3dfbc_thumb_110x88", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap G0A3377_copy_110x88 {
            get {
                object obj = ResourceManager.GetObject("G0A3377-copy_110x88", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap G0A3507_copy_110x88 {
            get {
                object obj = ResourceManager.GetObject("G0A3507-copy_110x88", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap G0A3530_copy_110x88 {
            get {
                object obj = ResourceManager.GetObject("G0A3530-copy_110x88", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap hacapuri_pide_limonata_225x526 {
            get {
                object obj = ResourceManager.GetObject("hacapuri-pide-limonata_225x526", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap Happy_Bubble_Iced_Tea_110x88 {
            get {
                object obj = ResourceManager.GetObject("Happy-Bubble-Iced-Tea_110x88", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap Hippy_Lychee_Iced_Tea_110x88 {
            get {
                object obj = ResourceManager.GetObject("Hippy-Lychee-Iced-Tea_110x88", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap humus_guacamole_110x88 {
            get {
                object obj = ResourceManager.GetObject("humus-guacamole_110x88", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap Iced_Amricano_e1601294609157_110x88 {
            get {
                object obj = ResourceManager.GetObject("Iced-Amricano-e1601294609157_110x88", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap IMG_0550_110x88 {
            get {
                object obj = ResourceManager.GetObject("IMG_0550_110x88", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap kaburga_burger_110x88 {
            get {
                object obj = ResourceManager.GetObject("kaburga-burger_110x88", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap kestaneli_kahveli_cheesecake_110x88 {
            get {
                object obj = ResourceManager.GetObject("kestaneli-kahveli-cheesecake_110x88", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap klasik_pizza {
            get {
                object obj = ResourceManager.GetObject("klasik-pizza", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap klasik_pizza_110x88 {
            get {
                object obj = ResourceManager.GetObject("klasik-pizza_110x88", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap köy_gözleme_patatesli_mozzarellalı_110x88 {
            get {
                object obj = ResourceManager.GetObject("köy-gözleme-patatesli-mozzarellalı_110x88", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap light_kahvaltı_tabağı__110x88 {
            get {
                object obj = ResourceManager.GetObject("light-kahvaltı-tabağı-_110x88", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap lotus_cheesecake_110x88 {
            get {
                object obj = ResourceManager.GetObject("lotus-cheesecake_110x88", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap MAKARNAPenne_artabiata_110x88 {
            get {
                object obj = ResourceManager.GetObject("MAKARNAPenne-artabiata_110x88", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap margherita_pizza_110x88 {
            get {
                object obj = ResourceManager.GetObject("margherita-pizza_110x88", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap menemen_110x88 {
            get {
                object obj = ResourceManager.GetObject("menemen_110x88", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap MGL0864_copy_110x88 {
            get {
                object obj = ResourceManager.GetObject("MGL0864-copy_110x88", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap MGL0870_copy_110x88 {
            get {
                object obj = ResourceManager.GetObject("MGL0870-copy_110x88", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap MGL0872_copy_110x88 {
            get {
                object obj = ResourceManager.GetObject("MGL0872-copy_110x88", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap MGL0879_copy_110x88 {
            get {
                object obj = ResourceManager.GetObject("MGL0879-copy_110x88", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap MGL0905_copy_110x88 {
            get {
                object obj = ResourceManager.GetObject("MGL0905-copy_110x88", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap MGL8015_copy {
            get {
                object obj = ResourceManager.GetObject("MGL8015-copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap MGL8015_copy1 {
            get {
                object obj = ResourceManager.GetObject("MGL8015-copy1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap MGL8064_copy_110x88 {
            get {
                object obj = ResourceManager.GetObject("MGL8064-copy_110x88", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap MGL9226_copy_110x88 {
            get {
                object obj = ResourceManager.GetObject("MGL9226-copy_110x88", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap MGL9244_copy_110x88 {
            get {
                object obj = ResourceManager.GetObject("MGL9244-copy_110x88", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap MGL9255_copy_110x88 {
            get {
                object obj = ResourceManager.GetObject("MGL9255-copy_110x88", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap MGL9258_copy_110x88 {
            get {
                object obj = ResourceManager.GetObject("MGL9258-copy_110x88", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap MGL9330_copy_110x88 {
            get {
                object obj = ResourceManager.GetObject("MGL9330-copy_110x88", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap MGL9364_copy_110x88 {
            get {
                object obj = ResourceManager.GetObject("MGL9364-copy_110x88", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap MGL9400_copy__1__110x88 {
            get {
                object obj = ResourceManager.GetObject("MGL9400-copy (1)_110x88", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap MGL9400_copy_200x100 {
            get {
                object obj = ResourceManager.GetObject("MGL9400-copy_200x100", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap MGL9400_copy_330x270 {
            get {
                object obj = ResourceManager.GetObject("MGL9400-copy_330x270", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap Mixberry_Milkshake_110x88 {
            get {
                object obj = ResourceManager.GetObject("Mixberry-Milkshake_110x88", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap Muzlu_çilekli_milkshakee_110x88 {
            get {
                object obj = ResourceManager.GetObject("Muzlu-çilekli-milkshakee_110x88", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap Mystic_Bubble_Iced_Tea__110x88 {
            get {
                object obj = ResourceManager.GetObject("Mystic-Bubble-Iced-Tea-_110x88", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap pexels_photo_20315946_225x526 {
            get {
                object obj = ResourceManager.GetObject("pexels-photo-20315946_225x526", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap Photo_21_11_2019_11_51_27_110x88 {
            get {
                object obj = ResourceManager.GetObject("Photo-21-11-2019-11-51-27_110x88", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap san_sebeastian_110x88 {
            get {
                object obj = ResourceManager.GetObject("san-sebeastian_110x88", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap Screen_Shot_2019_07_05_at_08_38_23_110x88 {
            get {
                object obj = ResourceManager.GetObject("Screen-Shot-2019-07-05-at-08.38.23_110x88", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap TATLItiramisu2_110x88 {
            get {
                object obj = ResourceManager.GetObject("TATLItiramisu2_110x88", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap TATLItiramisu2_110x881 {
            get {
                object obj = ResourceManager.GetObject("TATLItiramisu2_110x881", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap Tavuk_Külbastı_110x88 {
            get {
                object obj = ResourceManager.GetObject("Tavuk-Külbastı_110x88", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap tavuklu_sezar_salata_110x88 {
            get {
                object obj = ResourceManager.GetObject("tavuklu-sezar-salata_110x88", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap vegan_cheeseburger_110x88 {
            get {
                object obj = ResourceManager.GetObject("vegan-cheeseburger_110x88", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap vegan_cheeseburger_110x881 {
            get {
                object obj = ResourceManager.GetObject("vegan-cheeseburger_110x881", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap vegan_köfte_kase_110x88 {
            get {
                object obj = ResourceManager.GetObject("vegan-köfte-kase_110x88", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap vegan_köfte_salata_110x88 {
            get {
                object obj = ResourceManager.GetObject("vegan-köfte-salata_110x88", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap vegan_mozzarella_cedarli_tost_110x88 {
            get {
                object obj = ResourceManager.GetObject("vegan-mozzarella-cedarli-tost_110x88", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap veganporridge__110x88 {
            get {
                object obj = ResourceManager.GetObject("veganporridge-_110x88", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap WhatsApp_Image_2020_10_02_at_12_04_54_110x88 {
            get {
                object obj = ResourceManager.GetObject("WhatsApp-Image-2020-10-02-at-12.04.54_110x88", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap WhatsApp_Image_2020_10_02_at_12_04_56_1_110x88 {
            get {
                object obj = ResourceManager.GetObject("WhatsApp-Image-2020-10-02-at-12.04.56-1_110x88", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap WhatsApp_Image_2020_10_02_at_12_04_57_1_110x88 {
            get {
                object obj = ResourceManager.GetObject("WhatsApp-Image-2020-10-02-at-12.04.57-1_110x88", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap WhatsApp_Image_2020_10_02_at_12_04_57_110x88 {
            get {
                object obj = ResourceManager.GetObject("WhatsApp-Image-2020-10-02-at-12.04.57_110x88", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap WhatsApp_Image_2023_04_24_at_13_34_57_110x88 {
            get {
                object obj = ResourceManager.GetObject("WhatsApp-Image-2023-04-24-at-13.34.57_110x88", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap WhatsApp_Image_2023_05_11_at_12_35_46_110x88 {
            get {
                object obj = ResourceManager.GetObject("WhatsApp-Image-2023-05-11-at-12.35.46_110x88", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap WhatsApp_Image_2023_08_14_at_12_50_05_110x88 {
            get {
                object obj = ResourceManager.GetObject("WhatsApp-Image-2023-08-14-at-12.50.05_110x88", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
